services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
      POSTGRES_DB: invoice_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoice_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: invoice_pass
      POSTGRES_DB: invoice_test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invoice_user -d invoice_test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
